const { contextBridge, ipcRenderer, webUtils } = require('electron');

contextBridge.exposeInMainWorld('galaxy', {
  load: () => ipcRenderer.invoke('galaxy:load'),
  save: (project) => ipcRenderer.invoke('galaxy:save', project),
  openFolder: (p) => ipcRenderer.invoke('galaxy:openFolder', p),
  openClaude: (p) => ipcRenderer.invoke('galaxy:openClaude', p),
  tree: (p) => ipcRenderer.invoke('galaxy:tree', p),
  list: (root, rel) => ipcRenderer.invoke('galaxy:list', { root, rel }),
  file: (root, rel) => ipcRenderer.invoke('galaxy:file', { root, rel }),
  openFile: (p) => ipcRenderer.invoke('galaxy:openFile', p),
  readme: (p) => ipcRenderer.invoke('galaxy:readme', p),
  fileWrite: (opts) => ipcRenderer.invoke('galaxy:fileWrite', opts),
  fileCreate: (opts) => ipcRenderer.invoke('galaxy:fileCreate', opts),
  fileDelete: (opts) => ipcRenderer.invoke('galaxy:fileDelete', opts),
  fileRename: (opts) => ipcRenderer.invoke('galaxy:fileRename', opts),
  projectGrep: (opts) => ipcRenderer.invoke('galaxy:projectGrep', opts),
  claudeRun: (opts) => ipcRenderer.invoke('galaxy:claudeRun', opts),
  assistantRun: (opts) => ipcRenderer.invoke('galaxy:assistantRun', opts),
  checkUpdate: () => ipcRenderer.invoke('galaxy:checkUpdate'),
  openUpdate: (url) => ipcRenderer.invoke('galaxy:openUpdate', url),
  onUpdate: (cb) => { ipcRenderer.on('update:available', (e, p) => cb('available', p)); ipcRenderer.on('update:none', (e, p) => cb('none', p)); ipcRenderer.on('update:error', (e, p) => cb('error', p)); },
  asstHistoryGet: () => ipcRenderer.invoke('galaxy:asstHistoryGet'),
  asstHistoryAppend: (msg) => ipcRenderer.invoke('galaxy:asstHistoryAppend', msg),
  asstHistoryClear: () => ipcRenderer.invoke('galaxy:asstHistoryClear'),
  sttAvailable: () => ipcRenderer.invoke('galaxy:sttAvailable'),
  sttStart: () => ipcRenderer.invoke('galaxy:sttStart'),
  sttStop: () => ipcRenderer.invoke('galaxy:sttStop'),
  onStt: (cb) => ipcRenderer.on('stt:out', (e, msg) => cb(msg)),
  claudeStop: (runId) => ipcRenderer.invoke('galaxy:claudeStop', runId),
  onClaude: (cb) => ipcRenderer.on('claude:out', (e, msg) => cb(msg)),
  agentRun: (opts) => ipcRenderer.invoke('galaxy:agentRun', opts),
  onAgent: (cb) => ipcRenderer.on('agent:out', (e, msg) => cb(msg)),
  reports: () => ipcRenderer.invoke('galaxy:reports'),
  report: (name) => ipcRenderer.invoke('galaxy:report', name),
  openReportFile: (name) => ipcRenderer.invoke('galaxy:openReportFile', name),
  logDetect: (text) => ipcRenderer.invoke('galaxy:logDetect', text),
  logApply: (opts) => ipcRenderer.invoke('galaxy:logApply', opts),
  logSave: (text) => ipcRenderer.invoke('galaxy:logSave', text),
  logList: () => ipcRenderer.invoke('galaxy:logList'),
  universeAdd: (opts) => ipcRenderer.invoke('galaxy:universeAdd', opts),
  universeUpdate: (opts) => ipcRenderer.invoke('galaxy:universeUpdate', opts),
  universeDelete: (id) => ipcRenderer.invoke('galaxy:universeDelete', id),
  todoList: (universe) => ipcRenderer.invoke('galaxy:todoList', universe),
  todoAdd: (opts) => ipcRenderer.invoke('galaxy:todoAdd', opts),
  todoToggle: (id) => ipcRenderer.invoke('galaxy:todoToggle', id),
  todoDelete: (id) => ipcRenderer.invoke('galaxy:todoDelete', id),
  todoSetStatus: (opts) => ipcRenderer.invoke('galaxy:todoSetStatus', opts),
  syncReadme: (projectId) => ipcRenderer.invoke('galaxy:syncReadme', projectId),
  createReadme: (projectId) => ipcRenderer.invoke('galaxy:createReadme', projectId),
  projectDelete: (projectId) => ipcRenderer.invoke('galaxy:projectDelete', projectId),
  projectUnhide: (projectId) => ipcRenderer.invoke('galaxy:projectUnhide', projectId),
  gitLog: (projectId) => ipcRenderer.invoke('galaxy:gitLog', projectId),
  gitStage: (opts) => ipcRenderer.invoke('galaxy:gitStage', opts),
  gitUnstage: (opts) => ipcRenderer.invoke('galaxy:gitUnstage', opts),
  gitCommit: (opts) => ipcRenderer.invoke('galaxy:gitCommit', opts),
  gitPush: (opts) => ipcRenderer.invoke('galaxy:gitPush', opts),
  gitPull: (opts) => ipcRenderer.invoke('galaxy:gitPull', opts),
  gitSwitch: (opts) => ipcRenderer.invoke('galaxy:gitSwitch', opts),
  gitDiff: (opts) => ipcRenderer.invoke('galaxy:gitDiff', opts),
  agentsFull: () => ipcRenderer.invoke('galaxy:agentsFull'),
  agentSave: (agent) => ipcRenderer.invoke('galaxy:agentSave', agent),
  agentDelete: (id) => ipcRenderer.invoke('galaxy:agentDelete', id),
  dbList: () => ipcRenderer.invoke('galaxy:dbList'),
  dbSave: (db) => ipcRenderer.invoke('galaxy:dbSave', db),
  dbDelete: (id) => ipcRenderer.invoke('galaxy:dbDelete', id),
  dbTest: (cfg) => ipcRenderer.invoke('galaxy:dbTest', cfg),
  dbTables: (opts) => ipcRenderer.invoke('galaxy:dbTables', opts),
  dbQuery: (opts) => ipcRenderer.invoke('galaxy:dbQuery', opts),
  dbExec: (opts) => ipcRenderer.invoke('galaxy:dbExec', opts),
  dbAgent: (opts) => ipcRenderer.invoke('galaxy:dbAgent', opts),
  dbRows: (opts) => ipcRenderer.invoke('galaxy:dbRows', opts),
  dbInsertRow: (opts) => ipcRenderer.invoke('galaxy:dbInsertRow', opts),
  dbExportCsv: (opts) => ipcRenderer.invoke('galaxy:dbExportCsv', opts),
  dbUpdateRow: (opts) => ipcRenderer.invoke('galaxy:dbUpdateRow', opts),
  dbDeleteRow: (opts) => ipcRenderer.invoke('galaxy:dbDeleteRow', opts),
  dbLog: () => ipcRenderer.invoke('galaxy:dbLog'),
  dbLogClear: () => ipcRenderer.invoke('galaxy:dbLogClear'),
  dbDatabases: (id) => ipcRenderer.invoke('galaxy:dbDatabases', id),
  dbSchema: (opts) => ipcRenderer.invoke('galaxy:dbSchema', opts),
  openTerminal: (p) => ipcRenderer.invoke('galaxy:openTerminal', p),
  scheduleList: () => ipcRenderer.invoke('galaxy:scheduleList'),
  scheduleSave: (s) => ipcRenderer.invoke('galaxy:scheduleSave', s),
  scheduleDelete: (id) => ipcRenderer.invoke('galaxy:scheduleDelete', id),
  scheduleRun: (id) => ipcRenderer.invoke('galaxy:scheduleRun', id),
  onScheduleDone: (cb) => ipcRenderer.on('schedule:done', (e, msg) => cb(msg)),
  shellStart: (opts) => ipcRenderer.invoke('galaxy:shellStart', opts),
  shellInput: (opts) => ipcRenderer.invoke('galaxy:shellInput', opts),
  sshShellStart: (opts) => ipcRenderer.invoke('galaxy:sshShellStart', opts),
  sshShellInput: (opts) => ipcRenderer.invoke('galaxy:sshShellInput', opts),
  shellStop: (shellId) => ipcRenderer.invoke('galaxy:shellStop', shellId),
  shellComplete: (opts) => ipcRenderer.invoke('galaxy:shellComplete', opts),
  onShell: (cb) => ipcRenderer.on('shell:out', (e, msg) => cb(msg)),
  onboardStatus: () => ipcRenderer.invoke('galaxy:onboardStatus'),
  onboardComplete: (payload) => ipcRenderer.invoke('galaxy:onboardComplete', payload),
  profileGet: () => ipcRenderer.invoke('galaxy:profileGet'),
  openSettings: () => ipcRenderer.invoke('galaxy:openSettings'),
  settingsGet: () => ipcRenderer.invoke('galaxy:settingsGet'),
  settingsSave: (p) => ipcRenderer.invoke('galaxy:settingsSave', p),
  backupList: () => ipcRenderer.invoke('galaxy:backupList'),
  backupRestore: (name) => ipcRenderer.invoke('galaxy:backupRestore', name),

  // ---- Docker ----
  dockerStatus: () => ipcRenderer.invoke('galaxy:dockerStatus'),
  dockerStart: () => ipcRenderer.invoke('galaxy:dockerStart'),
  dockerPs: (all) => ipcRenderer.invoke('galaxy:dockerPs', all),
  dockerImages: () => ipcRenderer.invoke('galaxy:dockerImages'),
  dockerAction: (payload) => ipcRenderer.invoke('galaxy:dockerAction', payload),
  dockerImageAction: (payload) => ipcRenderer.invoke('galaxy:dockerImageAction', payload),
  dockerLogs: (payload) => ipcRenderer.invoke('galaxy:dockerLogs', payload),
  dockerLogStream: (payload) => ipcRenderer.invoke('galaxy:dockerLogStream', payload),
  dockerLogStop: (payload) => ipcRenderer.invoke('galaxy:dockerLogStop', payload),
  dockerExec: (payload) => ipcRenderer.invoke('galaxy:dockerExec', payload),
  onDockerLog: (cb) => ipcRenderer.on('docker:log', (e, msg) => cb(msg)),
  dockerPrune: (kind) => ipcRenderer.invoke('galaxy:dockerPrune', kind),
  openLocalPort: (port) => ipcRenderer.invoke('galaxy:openLocalPort', port),

  // ---- Uzak sunucu (SSH) ----
  sshConfigHosts: () => ipcRenderer.invoke('galaxy:sshConfigHosts'),
  sshKeys: () => ipcRenderer.invoke('galaxy:sshKeys'),
  sshList: () => ipcRenderer.invoke('galaxy:sshList'),
  sshSave: (srv) => ipcRenderer.invoke('galaxy:sshSave', srv),
  sshDelete: (id) => ipcRenderer.invoke('galaxy:sshDelete', id),
  sshTest: (srv) => ipcRenderer.invoke('galaxy:sshTest', srv),
  sshScan: (id) => ipcRenderer.invoke('galaxy:sshScan', id),
  pickFolder: () => ipcRenderer.invoke('galaxy:pickFolder'),
  pickFiles: () => ipcRenderer.invoke('galaxy:pickFiles'),
  pasteImage: () => ipcRenderer.invoke('galaxy:pasteImage'),
  saveAttachment: (opts) => ipcRenderer.invoke('galaxy:saveAttachment', opts),
  getPathForFile: (file) => { try { return webUtils.getPathForFile(file); } catch (e) { return file.path || null; } }
});
