const { contextBridge, ipcRenderer } = require('electron');

contextBridge.exposeInMainWorld('galaxy', {
  load: () => ipcRenderer.invoke('galaxy:load'),
  save: (project) => ipcRenderer.invoke('galaxy:save', project),
  openFolder: (p) => ipcRenderer.invoke('galaxy:openFolder', p),
  openClaude: (p) => ipcRenderer.invoke('galaxy:openClaude', p),
  tree: (p) => ipcRenderer.invoke('galaxy:tree', p),
  list: (root, rel) => ipcRenderer.invoke('galaxy:list', { root, rel }),
  file: (root, rel) => ipcRenderer.invoke('galaxy:file', { root, rel }),
  openFile: (p) => ipcRenderer.invoke('galaxy:openFile', p),
  readme: (p) => ipcRenderer.invoke('galaxy:readme', p),
  claudeRun: (opts) => ipcRenderer.invoke('galaxy:claudeRun', opts),
  claudeStop: (runId) => ipcRenderer.invoke('galaxy:claudeStop', runId),
  onClaude: (cb) => ipcRenderer.on('claude:out', (e, msg) => cb(msg)),
  agentRun: (opts) => ipcRenderer.invoke('galaxy:agentRun', opts),
  onAgent: (cb) => ipcRenderer.on('agent:out', (e, msg) => cb(msg)),
  reports: () => ipcRenderer.invoke('galaxy:reports'),
  report: (name) => ipcRenderer.invoke('galaxy:report', name),
  logDetect: (text) => ipcRenderer.invoke('galaxy:logDetect', text),
  logApply: (opts) => ipcRenderer.invoke('galaxy:logApply', opts),
  logSave: (text) => ipcRenderer.invoke('galaxy:logSave', text),
  logList: () => ipcRenderer.invoke('galaxy:logList'),
  universeAdd: (opts) => ipcRenderer.invoke('galaxy:universeAdd', opts),
  universeUpdate: (opts) => ipcRenderer.invoke('galaxy:universeUpdate', opts),
  universeDelete: (id) => ipcRenderer.invoke('galaxy:universeDelete', id),
  todoList: (universe) => ipcRenderer.invoke('galaxy:todoList', universe),
  todoAdd: (opts) => ipcRenderer.invoke('galaxy:todoAdd', opts),
  todoToggle: (id) => ipcRenderer.invoke('galaxy:todoToggle', id),
  todoDelete: (id) => ipcRenderer.invoke('galaxy:todoDelete', id),
  todoSetStatus: (opts) => ipcRenderer.invoke('galaxy:todoSetStatus', opts),
  syncReadme: (projectId) => ipcRenderer.invoke('galaxy:syncReadme', projectId),
  projectDelete: (projectId) => ipcRenderer.invoke('galaxy:projectDelete', projectId),
  projectUnhide: (projectId) => ipcRenderer.invoke('galaxy:projectUnhide', projectId),
  gitLog: (projectId) => ipcRenderer.invoke('galaxy:gitLog', projectId),
  agentsFull: () => ipcRenderer.invoke('galaxy:agentsFull'),
  agentSave: (agent) => ipcRenderer.invoke('galaxy:agentSave', agent),
  agentDelete: (id) => ipcRenderer.invoke('galaxy:agentDelete', id),
  dbList: () => ipcRenderer.invoke('galaxy:dbList'),
  dbSave: (db) => ipcRenderer.invoke('galaxy:dbSave', db),
  dbDelete: (id) => ipcRenderer.invoke('galaxy:dbDelete', id),
  dbTest: (cfg) => ipcRenderer.invoke('galaxy:dbTest', cfg),
  dbTables: (id) => ipcRenderer.invoke('galaxy:dbTables', id),
  dbQuery: (opts) => ipcRenderer.invoke('galaxy:dbQuery', opts),
  openTerminal: (p) => ipcRenderer.invoke('galaxy:openTerminal', p),
  scheduleList: () => ipcRenderer.invoke('galaxy:scheduleList'),
  scheduleSave: (s) => ipcRenderer.invoke('galaxy:scheduleSave', s),
  scheduleDelete: (id) => ipcRenderer.invoke('galaxy:scheduleDelete', id),
  scheduleRun: (id) => ipcRenderer.invoke('galaxy:scheduleRun', id),
  onScheduleDone: (cb) => ipcRenderer.on('schedule:done', (e, msg) => cb(msg)),
  shellStart: (opts) => ipcRenderer.invoke('galaxy:shellStart', opts),
  shellInput: (opts) => ipcRenderer.invoke('galaxy:shellInput', opts),
  shellStop: (shellId) => ipcRenderer.invoke('galaxy:shellStop', shellId),
  onShell: (cb) => ipcRenderer.on('shell:out', (e, msg) => cb(msg)),
  pickFiles: () => ipcRenderer.invoke('galaxy:pickFiles')
});
